const WRONG_DATA_CODE = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND_CODE = 404;
const ERROR_SERVER_CODE = 500;
const MONGO_DB_CODE = 11000;

module.exports = {
  WRONG_DATA_CODE, UNAUTHORIZED, NOT_FOUND_CODE, ERROR_SERVER_CODE, MONGO_DB_CODE,
};
